name: levicsmith
favicon: null
layout_spectrum: 0.04042553
typography_spectrum: 0.3689
title: Levi C Smith || BLOG
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#110c09'
    - '#fffcf3'
    - '#a48779'
    - '#5b4940'
    - '#dfcdb4'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
