name: levicsmith
favicon: null
layout_spectrum: 0.48844
typography_spectrum: 0.3689
title: Levi C Smith
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090806'
    - '#d1cbcf'
    - '#0184a2'
    - '#816a48'
    - '#ec0030'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
