title: 'Levi C Smith || BLOG'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9375
  brandStrength: 0.125
  rhythmicContrast: 0.75
  brandColors:
    - '#110c09'
    - '#fffcf3'
    - '#a48779'
    - '#5b4940'
    - '#dfcdb4'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: levicsmith
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3689
layout_spectrum: 0.04042553
